'use client'
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'id';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>('en');
    const [mounted, setMounted] = useState(false);

    useEffect(() => {
        const saved = localStorage.getItem('language') as Language;
        if (saved) setLanguage(saved);
        setMounted(true);
    }, []);

    const changeLanguage = (lang: Language) => {
        setLanguage(lang);
        localStorage.setItem('language', lang);
    };

    // Simple dictionary
    const dictionary: Record<Language, Record<string, string>> = {
        en: {
            "Dashboard": "Dashboard",
            "Agent": "Agent",
            "Bot Builder": "Bot Builder",
            "Integration": "Integration",
            "Customers": "Customers",
            "Products": "Products",
            "Sales Monitoring": "Sales Monitoring",
            "Payments": "Payments",
            "AI Analytics": "AI Analytics",
            "Notifications": "Notifications",
            "Settings": "Settings",
            "Platform Dashboard": "Platform Dashboard",
            "Premium Access": "Premium Access",
            "Overview": "Overview",
            "Core": "Core",
            "Management": "Management",
            "Sales & Finance": "Sales & Finance",
            "Analytics": "Analytics",
            "System": "System",
            "Super Admin": "Super Admin",
            "Status": "Status",
            "FREE PLAN": "FREE PLAN",
            "PRO PLAN": "PRO PLAN",
            "Free Workspace": "Free Workspace",
            "Pro Workspace": "Pro Workspace",
            "Upgrade to Pro": "Upgrade to Pro",
            "Pro Feature Active": "Pro Feature Active",
            "Global Overview": "Global Overview",
            "Platform Stats": "Platform Stats",
            "All Users": "All Users",
            "All": "All",
            "Sales": "Sales",
            "Organizations": "Organizations",
            "Subscriptions": "Subscriptions",
            "Media Monitoring": "Media Monitoring",
            "Nodes Status": "Nodes Status",
            "Traffic Logs": "Traffic Logs",
            "Database Health": "Database Health",
            "System Settings": "System Settings",
            "Security & Auth": "Security & Auth",
            "Global Plugins": "Global Plugins",
            "Advanced analytics overview for your Pro workspace.": "Advanced analytics overview for your Pro workspace.",
            "Welcome back! Here's your analytics overview.": "Welcome back! Here's your analytics overview.",
            "You": "You",
            "No Company": "No Company",
            "Back": "Back",
            "Chat Support": "Chat Support",
            "Halo! Ada yang bisa kami bantu hari ini?": "Hello! How can we help you today?",
            "Clean up stuck WhatsApp integrations? This will delete all integrations stuck in \"connecting\" status for more than 5 minutes.": "Clean up stuck WhatsApp integrations? This will delete all integrations stuck in \"connecting\" status for more than 5 minutes.",
            "Cleaned up": "Cleaned up",
            "stuck integration(s)": "stuck integration(s)",
            "All your bots are already connected or no bots found.": "All your bots are already connected or no bots found.",
            "Create a new bot in Bot Builder first.": "Create a new bot in Bot Builder first.",
            "Copy & Activate": "Copy & Activate",
            "Copied! Status updated to Active.": "Copied! Status updated to Active.",
            "Simulation successful. Integration entry will show up in your list.": "Simulation successful. Integration entry will show up in your list.",
            "AI Agents": "AI Agents",
            "Active Bots": "Active Bots",
            "AI Interactions": "AI Interactions",
            "Total Leads": "Total Leads",
            "vs last month": "vs last month",
            "Real-time accumulation data": "Real-time accumulation data",
            "User Growth": "User Growth",
            "Bot Usage Growth": "Bot Usage Growth",
            "New Users": "New Users",
            "Bots Created": "Bots Created",
            "System Volume": "System Volume",
            "Bot Interactions": "Bot Interactions",
            "Activity metrics": "Activity metrics",
            "Active": "Active",
            "Real-time": "Real-time",

            // Customers
            "Edit Profile": "Edit Profile",
            "New Customer": "New Customer",
            "Manage your customer database and interactions.": "Manage your customer database and interactions.",
            "Add new customer detail information.": "Add new customer detail information.",
            "Add Customer": "Add Customer",
            "Total Customers": "Total Customers",
            "Active Leads": "Active Leads",
            "Search by name or email...": "Search by name or email...",
            "No customer data yet.": "No customer data yet.",
            "Customer": "Customer",
            "Contact": "Contact",
            "Joined Date": "Joined Date",
            "Join Date": "Join Date",
            "Full Name": "Full Name",
            "Search users by name or email...": "Search users by name or email...",
            "Editor": "Editor",
            "Pending": "Pending",
            "Phone Number": "Phone Number",
            "Customer Status": "Customer Status",
            "Lead (Prospect)": "Lead (Prospect)",
            "Active (Customer)": "Active (Customer)",
            "Inactive": "Inactive",
            "Update Profile": "Update Profile",
            "Add to Database": "Add to Database",
            "Name is required!": "Name is required!",
            "Failed to save: ": "Failed to save: ",
            "Delete this customer data?": "Delete this customer data?",
            "Failed to delete": "Failed to delete",

            // Settings
            "Manage your account and preferences.": "Manage your account and preferences.",
            "Profile Information": "Profile Information",
            "User Pro": "User Pro",
            "Profile Picture": "Profile Picture",
            "Upload a new photo. Recommended size 400x400px.": "Upload a new photo. Recommended size 400x400px.",
            "Change Photo": "Change Photo",
            "Remove": "Remove",
            "Email cannot be changed directly.": "Email cannot be changed directly.",
            "Company Name": "Company Name",
            "Saving...": "Saving...",
            "Saved Changes": "Saved Changes",
            "Save Profile": "Save Profile",
            "Security & Password": "Security & Password",
            "Password": "Password",
            "For security reasons, your current password is hidden. You can change it below.": "For security reasons, your current password is hidden. You can change it below.",
            "Change Password": "Change Password",
            "Enter your new password below.": "Enter your new password below.",
            "New Password": "New Password",
            "Confirm Password": "Confirm Password",
            "Update Password": "Update Password",
            "Two-Factor Authentication": "Two-Factor Authentication",
            "Add an extra layer of security to your account.": "Add an extra layer of security to your account.",
            "Enable 2FA (Coming Soon)": "Enable 2FA (Coming Soon)",
            "Preferences": "Preferences",
            "Timezone": "Timezone",
            "Language": "Language",
            "English": "English",
            "Indonesian": "Indonesian",
            "UTC": "UTC",
            "Eastern Time": "Eastern Time",
            "Theme": "Theme",
            "Light": "Light",
            "Dark": "Dark",
            "Select theme": "Select theme",
            "Danger Zone": "Danger Zone",
            "Delete Account": "Delete Account",
            "Permanently delete your account and all associated data.": "Permanently delete your account and all associated data.",
            "This action cannot be undone. This will permanently delete your account and remove your data from our servers.": "This action cannot be undone. This will permanently delete your account and remove your data from our servers.",
            "Confirm Delete": "Confirm Delete",
            "Passwords do not match": "Passwords do not match",
            "Password must be at least 6 characters": "Password must be at least 6 characters",
            "Password updated successfully": "Password updated successfully",
            "Failed to update password: ": "Failed to update password: ",
            "Failed to delete account: ": "Failed to delete account: ",
            "Failed to save profile: ": "Failed to save profile: ",
            "Loading settings...": "Loading settings...",
            "Type": "Type",
            "to confirm": "to confirm",
            "Cancel": "Cancel",

            // Products
            "Product Catalog": "Product Catalog",
            "Edit Product": "Edit Product",
            "New Product": "New Product",
            "Used": "Used",
            "Manage your catalog and categories.": "Manage your catalog and categories.",
            "Categories": "Categories",
            "Manage Categories": "Manage Categories",
            "New category name...": "New category name...",
            "Limit Reached": "Limit Reached",
            "Add Product": "Add Product",
            "Search products...": "Search products...",
            "No products found.": "No products found.",
            "Start by adding a new product to your catalog.": "Start by adding a new product to your catalog.",
            "Product Image": "Product Image",
            "No Image Selected": "No Image Selected",
            "Choose Image": "Choose Image",
            "Remove Image": "Remove Image",
            "Product Name": "Product Name",
            "Category": "Category",
            "Price (IDR)": "Price (IDR)",
            "Stock": "Stock",
            "Description": "Description",
            "Update Product": "Update Product",
            "Save Product": "Save Product",
            "Product details...": "Product details...",
            "Name and Price are required!": "Name and Price are required!",
            "Failed to save product": "Failed to save product",
            "Failed to delete product": "Failed to delete product",
            "Delete this product?": "Delete this product?",
            "Category 'General' cannot be deleted.": "Category 'General' cannot be deleted.",
            "Uploading...": "Uploading...",
            "Unlock Unlimited Products! 🚀": "Unlock Unlimited Products! 🚀",
            "Upgrade to PRO plan to upload unlimited products and boost your sales.": "Upgrade to PRO plan to upload unlimited products and boost your sales.",
            "Upgrade Now ⚡": "Upgrade Now ⚡",
            "No description available.": "No description available.",

            // Sales Monitoring
            "Real-time transaction data from database.": "Real-time transaction data from database.",
            "Add Transaction": "Add Transaction",
            "New Transaction": "New Transaction",
            "Product": "Product",
            "Amount (IDR)": "Amount (IDR)",
            "Save Transaction": "Save Transaction",
            "Total Revenue": "Total Revenue",
            "Orders Processed": "Orders Processed",
            "Avg. Order Value": "Avg. Order Value",
            "Recent Transactions": "Recent Transactions",
            "Search orders...": "Search orders...",
            "Order ID": "Order ID",
            "Date": "Date",
            "Action": "Action",
            "Completed": "Completed",
            "Cancelled": "Cancelled",
            "Delete this transaction?": "Delete this transaction?",
            "Please fill all fields": "Please fill all fields",
            "Failed to create sale": "Failed to create sale",
            "No sales data found.": "No sales data found.",
            "Add your first transaction": "Add your first transaction",
            "Refresh Data": "Refresh Data",
            "Loading data...": "Loading data...",
            "Calculated": "Calculated",
            "Updated": "Updated",

            // Agent
            "Agent Name is required!": "Agent Name is required!",
            "Failed to save agent": "Failed to save agent",
            "Are you sure you want to delete this agent?": "Are you sure you want to delete this agent?",
            "Failed to delete agent": "Failed to delete agent",
            "Edit Agent": "Edit Agent",
            "Create Agent": "Create Agent",
            "Manage your AI assistants.": "Manage your AI assistants.",
            "Configure identity, knowledge, and products.": "Configure identity, knowledge, and products.",
            "Test": "Test",
            "No agents found. Create your first agent!": "No agents found. Create your first agent!",
            "No documents uploaded.": "No documents uploaded.",
            "+ Add Knowledge File": "+ Add Knowledge File",
            "Upload error": "Upload error",
            "Agent Name": "Agent Name",
            "Model Engine": "Model Engine",
            "Agent Products": "Agent Products",
            "Select products this agent can recommend.": "Select products this agent can recommend.",
            "Select from Catalog": "Select from Catalog",
            "Or Add Manual Item (Optional)": "Or Add Manual Item (Optional)",
            "Manual Product Name": "Manual Product Name",
            "Price (e.g. Rp 50.000)": "Price (e.g. Rp 50.000)",
            "Short Description": "Short Description",
            "No description": "No description",
            "No products added yet.": "No products added yet.",
            "Peran & Gaya Bicara (Role & Tone)": "Role & Tone",
            "Pilih peran & sifat AI...": "Choose AI role & tone...",
            "Memilih opsi peran di atas akan otomatis mengisi Instruksi Dasar di bawah.": "Choosing a role above will automatically fill the Basic Instructions below.",
            "System Prompt": "System Prompt",
            "Define behavior...": "Define behavior...",
            "Live Simulator": "Live Simulator",
            "Thinking...": "Thinking...",
            "Type something...": "Type something...",
            "Import from Catalog": "Import from Catalog",
            "Select products to add to your agent's knowledge base.": "Select products to add to your agent's knowledge base.",
            "No products found in catalog.": "No products found in catalog.",
            "Go to Product Manager": "Go to Product Manager",
            "Import": "Import",

            // Bot Builder
            "Please complete bot data!": "Please complete bot data!",
            "Failed to create bot": "Failed to create bot",
            "Delete this bot?": "Delete this bot?",
            "Failed to delete bot": "Failed to delete bot",
            "Connect your AI Agents to your preferred platforms.": "Connect your AI Agents to your preferred platforms.",
            "Back to List": "Back to List",
            "No bots connected yet.": "No bots connected yet.",
            "Add your first bot": "Add your first bot",
            "Configure New Bot": "Configure New Bot",
            "Link an AI personality to a messaging platform.": "Link an AI personality to a messaging platform.",
            "Bot Name": "Bot Name",
            "Select AI Agent": "Select AI Agent",
            "Choose Agent": "Choose Agent",
            "No agents found": "No agents found",
            "Choose Platform": "Choose Platform",
            "Create Bot Instance": "Create Bot Instance",

            // AI Analytics
            "Insight cerdas dari percakapan dan perilaku pelanggan Anda.": "Smart insights from your conversations and customer behavior.",
            "Generate Report": "Generate Report",
            "Chat Resolution": "Chat Resolution",
            "Avg. Sentiment": "Avg. Sentiment",
            "Conversion Rate": "Conversion Rate",
            "AI Messages": "AI Messages",
            "Conversion Funnel": "Conversion Funnel",
            "This Week": "This Week",
            "This Month": "This Month",
            "Rekomendasi AI": "AI Recommendation",
            "Top Customer Intents": "Top Customer Intents",
            "messages": "messages",
            "Detailed Chat Sentiment History": "Detailed Chat Sentiment History",
            "Visualisasi tren kepuasan pelanggan secara harian akan muncul di sini menggunakan": "Daily customer satisfaction trend visualization will appear here using",
            "Connect Analytics Database": "Connect Analytics Database",

            // Integrations
            "Integrations": "Integrations",
            "Manage your chatbot connections and live channels.": "Manage your chatbot connections and live channels.",
            "Cleanup": "Cleanup",
            "Add Connection": "Add Connection",
            "Select Platform": "Select Platform",
            "Active Connections": "Active Connections",
            "Disconnect integration?": "Disconnect integration?",
            "Belum ada bot yang dibuat Bang.": "No bots created yet.",
            "Pergi ke Bot Builder dulu yuk 🚀": "Go to Bot Builder first 🚀",
            "Scan QR Code": "Scan QR Code",
            "Link your chatbot in seconds.": "Link your chatbot in seconds.",
            "Live Preview": "Live Preview",
            "Widget Title": "Widget Title",
            "Theme Color": "Theme Color",
            "Welcome Message": "Welcome Message",
            "Create Widget & Get Code": "Create Widget & Get Code",
            "Select Bot to Connect": "Select Bot to Connect",
            "Choose a bot from Builder": "Choose a bot from Builder",
            "Skip (Broadcast Only / Manual Chat)": "Skip (Broadcast Only / Manual Chat)",
            "Start Connection & Get QR": "Start Connection & Get QR",
            "Scan with your phone": "Scan with your phone",
            "Open WhatsApp > Settings > Linked Devices to scan this code.": "Open WhatsApp > Settings > Linked Devices to scan this code.",
            "I've Scanned": "I've Scanned",
            "Success!": "Success!",
            "Finish": "Finish",
            "Connect": "Connect",
            "Online": "Online",
            "Offline": "Offline",

            // Notifications
            "Pusat aktivitas real-time sistem Anda.": "Your system's real-time activity center.",
            "Delete All": "Delete All",
            "Mark All Read": "Mark All Read",
            "Unread": "Unread",
            "AI Bot": "AI Bot",
            "Select All": "Select All",
            "Delete this notification?": "Delete this notification?",
            "Delete selected notifications?": "Delete selected notifications?",
            "Kategori ini kosong": "This category is empty",

            // Payments
            "Payments & Automation": "Payments & Automation",
            "Kelola integrasi pembayaran dan sistem otomatisasi.": "Manage payment integrations and automation systems.",
            "AI Closing Logic": "AI Closing Logic",
            "Atur skenario closing otomatis untuk Bot Anda.": "Set up automatic closing scenarios for your Bot.",
            "AI Closing Mode": "AI Closing Mode",
            "ACTIVE": "ACTIVE",
            "DISABLED": "DISABLED",
            "Smart AI Closing": "Smart AI Closing",
            "Aktifkan deteksi niat beli dan kirim invoice otomatis ke pelanggan.": "Enable purchase intent detection and send automated invoices to customers.",
            "Setup Bot Logic": "Setup Bot Logic",
            "Connected Gateways": "Connected Gateways",
            "NEEDS SETUP": "NEEDS SETUP",
            "CONNECTED": "CONNECTED",
            "Virtual Account & QRIS": "Virtual Account & QRIS",
            "Terima dana otomatis tanpa konfirmasi manual.": "Receive funds automatically without manual confirmation.",
            "Configure API Keys": "Configure API Keys",
            "Anti-Fraud Protection Active": "Anti-Fraud Protection Active",
            "Settlements": "Settlements",
            "Full History": "Full History",
            "Security": "Security",
            "Smart Logic": "Smart Logic",
            "Trigger Keywords": "Trigger Keywords",
            "Bot Closing Message": "Bot Closing Message",
            "Save Bot Logic": "Save Bot Logic",
            "Discard": "Discard",
            "Midtrans Keys": "Midtrans Keys",
            "Production Mode": "Production Mode",
            "Merchant ID": "Merchant ID",
            "Server Key": "Server Key",
            "Save & Connect": "Save & Connect",

            // Users
            "Users": "Users",
            "Manage and monitor all users in the system.": "Manage and monitor all users in the system.",
            "Add User": "Add User",
            "Name": "Name",
            "Email": "Email",
            "Role": "Role",
            "Actions": "Actions",
            "Previous": "Previous",
            "Next": "Next",
            "Showing": "Showing",
            "of": "of",
            "users": "users",
            "Logout": "Logout",
            "US": "US",
            "Knowledge Base": "Knowledge Base",
            "Live Chat / Inbox": "Live Chat / Inbox",
            "Campaign / Broadcast": "Campaign / Broadcast",
            "Loading...": "Loading...",
        },
        id: {
            "Dashboard": "Dasbor",
            "Agent": "Agen",
            "Bot Builder": "Pembuat Bot",
            "Integration": "Integrasi",
            "Customers": "Pelanggan",
            "Products": "Produk",
            "Sales Monitoring": "Pantau Penjualan",
            "Payments": "Pembayaran",
            "AI Analytics": "Analitik AI",
            "Notifications": "Notifikasi",
            "Settings": "Pengaturan",
            "Platform Dashboard": "Dasbor Platform",
            "Premium Access": "Akses Premium",
            "Overview": "Ringkasan",
            "Core": "Inti",
            "Management": "Manajemen",
            "Sales & Finance": "Keuangan",
            "Analytics": "Analitik",
            "System": "Sistem",
            "Super Admin": "Super Admin",
            "Status": "Status",
            "FREE PLAN": "PAKET GRATIS",
            "PRO PLAN": "PAKET PRO",
            "Free Workspace": "Ruang Kerja Gratis",
            "Pro Workspace": "Ruang Kerja Pro",
            "Upgrade to Pro": "Upgrade ke Pro",
            "Pro Feature Active": "Fitur Pro Aktif",
            "Global Overview": "Ringkasan Global",
            "Platform Stats": "Statistik Platform",
            "All Users": "Semua Pengguna",
            "All": "Semua",
            "Sales": "Penjualan",
            "Organizations": "Organisasi",
            "Subscriptions": "Langganan",
            "Media Monitoring": "Pantauan Media",
            "Nodes Status": "Status Node",
            "Traffic Logs": "Log Trafik",
            "Database Health": "Kesehatan Database",
            "System Settings": "Pengaturan Sistem",
            "Security & Auth": "Keamanan & Autentikasi",
            "Global Plugins": "Plugin Global",
            "Advanced analytics overview for your Pro workspace.": "Ringkasan analitik lanjutan untuk ruang kerja Pro Anda.",
            "Welcome back! Here's your analytics overview.": "Selamat datang kembali! Berikut ringkasan analitik Anda.",
            "You": "Anda",
            "No Company": "Tidak Ada Perusahaan",
            "Back": "Kembali",
            "Chat Support": "Bantuan Chat",
            "Halo! Ada yang bisa kami bantu hari ini?": "Halo! Ada yang bisa kami bantu hari ini?",
            "Clean up stuck WhatsApp integrations? This will delete all integrations stuck in \"connecting\" status for more than 5 minutes.": "Bersihkan integrasi WhatsApp yang macet? Ini akan menghapus semua integrasi yang tertahan di status \"menghubungkan\" selama lebih dari 5 menit.",
            "Cleaned up": "Berhasil dibersihkan",
            "stuck integration(s)": "integrasi yang macet",
            "All your bots are already connected or no bots found.": "Semua bot kamu sudah terhubung atau belum ada bot.",
            "Create a new bot in Bot Builder first.": "Buat bot baru di Bot Builder dulu ya Bang.",
            "Copy & Activate": "Salin & Aktifkan",
            "Copied! Status updated to Active.": "Berhasil disalin! Status diperbarui menjadi Aktif.",
            "Simulation successful. Integration entry will show up in your list.": "Simulasi berhasil. Entri integrasi akan muncul di daftar Anda.",
            "AI Agents": "Agen AI",
            "Active Bots": "Bot Aktif",
            "AI Interactions": "Interaksi AI",
            "Total Leads": "Total Prospek",
            "vs last month": "vs bulan lalu",
            "Real-time accumulation data": "Data akumulasi waktu nyata",
            "User Growth": "Pertumbuhan Pengguna",
            "Bot Usage Growth": "Pertumbuhan Penggunaan Bot",
            "New Users": "Pengguna Baru",
            "Bots Created": "Bot Dibuat",
            "System Volume": "Volume Sistem",
            "Bot Interactions": "Interaksi Bot",
            "Activity metrics": "Metrik aktivitas",
            "Active": "Aktif",
            "Real-time": "Waktu-nyata",

            // Customers
            "Edit Profile": "Edit Profil",
            "New Customer": "Pelanggan Baru",
            "Manage your customer database and interactions.": "Kelola database dan interaksi pelanggan Anda.",
            "Add new customer detail information.": "Tambahkan informasi detail pelanggan baru.",
            "Add Customer": "Tambah Pelanggan",
            "Total Customers": "Total Pelanggan",
            "Active Leads": "Prospek Aktif",
            "Search by name or email...": "Cari nama atau email...",
            "No customer data yet.": "Belum ada data pelanggan.",
            "Customer": "Pelanggan",
            "Contact": "Kontak",
            "Joined Date": "Tanggal Bergabung",
            "Join Date": "Tanggal Gabung",
            "Full Name": "Nama Lengkap",
            "Search users by name or email...": "Cari pengguna melalui nama atau email...",
            "Editor": "Editor",
            "Pending": "Tertunda",
            "Phone Number": "Nomor Telepon",
            "Customer Status": "Status Pelanggan",
            "Lead (Prospect)": "Ketertarikan (Prospek)",
            "Active (Customer)": "Aktif (Pelanggan)",
            "Inactive": "Tidak Aktif",
            "Update Profile": "Perbarui Profil",
            "Add to Database": "Tambahkan ke Database",
            "Name is required!": "Nama wajib diisi!",
            "Failed to save: ": "Gagal menyimpan: ",
            "Delete this customer data?": "Hapus data pelanggan ini?",
            "Failed to delete": "Gagal menghapus",

            // Settings
            "Manage your account and preferences.": "Kelola akun dan preferensi Anda.",
            "Profile Information": "Informasi Profil",
            "User Pro": "Pengguna Pro",
            "Profile Picture": "Foto Profil",
            "Upload a new photo. Recommended size 400x400px.": "Unggah foto baru. Ukuran disarankan 400x400px.",
            "Change Photo": "Ubah Foto",
            "Remove": "Hapus",
            "Email cannot be changed directly.": "Email tidak dapat diubah secara langsung.",
            "Company Name": "Nama Perusahaan",
            "Saving...": "Menyimpan...",
            "Saved Changes": "Perubahan Disimpan",
            "Save Profile": "Simpan Profil",
            "Security & Password": "Keamanan & Kata Sandi",
            "Password": "Kata Sandi",
            "For security reasons, your current password is hidden. You can change it below.": "Untuk alasan keamanan, kata sandi Anda saat ini disembunyikan. Anda dapat mengubahnya di bawah.",
            "Change Password": "Ubah Kata Sandi",
            "Enter your new password below.": "Masukkan kata sandi baru Anda di bawah.",
            "New Password": "Kata Sandi Baru",
            "Confirm Password": "Konfirmasi Kata Sandi",
            "Update Password": "Perbarui Kata Sandi",
            "Two-Factor Authentication": "Autentikasi Dua Faktor",
            "Add an extra layer of security to your account.": "Tambahkan lapisan keamanan ekstra ke akun Anda.",
            "Enable 2FA (Coming Soon)": "Aktifkan 2FA (Segera Hadir)",
            "Preferences": "Preferensi",
            "Timezone": "Zona Waktu",
            "Language": "Bahasa",
            "English": "Inggris",
            "Indonesian": "Indonesia",
            "UTC": "UTC",
            "Eastern Time": "Waktu Timur (EST)",
            "Theme": "Tema",
            "Light": "Terang",
            "Dark": "Gelap",
            "Select theme": "Pilih tema",
            "Danger Zone": "Zona Bahaya",
            "Delete Account": "Hapus Akun",
            "Permanently delete your account and all associated data.": "Hapus akun Anda dan semua data terkait secara permanen.",
            "This action cannot be undone. This will permanently delete your account and remove your data from our servers.": "Tindakan ini tidak dapat dibatalkan. Ini akan menghapus akun Anda secara permanen dan menghapus data Anda dari server kami.",
            "Confirm Delete": "Konfirmasi Hapus",
            "Passwords do not match": "Kata sandi tidak cocok",
            "Password must be at least 6 characters": "Kata sandi minimal 6 karakter",
            "Password updated successfully": "Kata sandi berhasil diperbarui",
            "Failed to update password: ": "Gagal memperbarui kata sandi: ",
            "Failed to delete account: ": "Gagal menghapus akun: ",
            "Failed to save profile: ": "Gagal menyimpan profil: ",
            "Loading settings...": "Memuat pengaturan...",
            "Type": "Ketik",
            "to confirm": "untuk konfirmasi",
            "Cancel": "Batal",

            // Products
            "Product Catalog": "Katalog Produk",
            "Edit Product": "Edit Produk",
            "New Product": "Produk Baru",
            "Used": "Terpakai",
            "Manage your catalog and categories.": "Kelola katalog dan kategori Anda.",
            "Categories": "Kategori",
            "Manage Categories": "Kelola Kategori",
            "New category name...": "Nama kategori baru...",
            "Limit Reached": "Batas Tercapai",
            "Add Product": "Tambah Produk",
            "Search products...": "Cari produk...",
            "No products found.": "Produk tidak ditemukan.",
            "Start by adding a new product to your catalog.": "Mulai dengan menambahkan produk baru ke katalog Anda.",
            "Product Image": "Foto Produk",
            "No Image Selected": "Belum Ada Foto",
            "Choose Image": "Pilih Foto",
            "Remove Image": "Hapus Foto",
            "Product Name": "Nama Produk",
            "Category": "Kategori",
            "Price (IDR)": "Harga (IDR)",
            "Stock": "Stok",
            "Description": "Deskripsi",
            "Update Product": "Perbarui Produk",
            "Save Product": "Simpan Produk",
            "Product details...": "Detail produk...",
            "Name and Price are required!": "Nama dan Harga wajib diisi!",
            "Failed to save product": "Gagal menyimpan produk",
            "Failed to delete product": "Gagal menghapus produk",
            "Delete this product?": "Yakin ingin menghapus produk ini?",
            "Category 'General' cannot be deleted.": "Kategori 'General' tidak bisa dihapus.",
            "Uploading...": "Mengunggah...",
            "Unlock Unlimited Products! \uD83D\uDE80": "Buka Produk Tanpa Batas! \uD83D\uDE80",
            "Upgrade to PRO plan to upload unlimited products and boost your sales.": "Upgrade ke paket PRO untuk mengunggah produk tanpa batas dan tingkatkan penjualan Anda.",
            "Upgrade Now \u26A1": "Upgrade Sekarang \u26A1",
            "No description available.": "Belum ada deskripsi.",

            // Sales Monitoring
            "Real-time transaction data from database.": "Data transaksi waktu-nyata dari database.",
            "Add Transaction": "Tambah Transaksi",
            "New Transaction": "Transaksi Baru",
            "Product": "Produk",
            "Amount (IDR)": "Jumlah (IDR)",
            "Save Transaction": "Simpan Transaksi",
            "Total Revenue": "Total Pendapatan",
            "Orders Processed": "Pesanan Diproses",
            "Avg. Order Value": "Rata-rata Nilai Pesanan",
            "Recent Transactions": "Transaksi Terbaru",
            "Search orders...": "Cari pesanan...",
            "Order ID": "ID Pesanan",
            "Date": "Tanggal",
            "Action": "Aksi",
            "Completed": "Selesai",
            "Cancelled": "Dibatalkan",
            "Delete this transaction?": "Hapus transaksi ini?",
            "Please fill all fields": "Mohon isi semua bidang",
            "Failed to create sale": "Gagal membuat penjualan",
            "No sales data found.": "Data penjualan tidak ditemukan.",
            "Add your first transaction": "Tambah transaksi pertama Anda",
            "Refresh Data": "Refresh Data",
            "Loading data...": "Memuat data...",
            "Calculated": "Dihitung",
            "Updated": "Diperbarui",

            // Agent
            "Agent Name is required!": "Nama Agent wajib diisi!",
            "Failed to save agent": "Gagal menyimpan agent",
            "Are you sure you want to delete this agent?": "Yakin ingin menghapus agent ini?",
            "Failed to delete agent": "Gagal menghapus agent",
            "Edit Agent": "Edit Agent",
            "Create Agent": "Buat Agent",
            "Manage your AI assistants.": "Kelola asisten AI Anda.",
            "Configure identity, knowledge, and products.": "Konfigurasi identitas, pengetahuan, dan produk.",
            "Test": "Tes",
            "No agents found. Create your first agent!": "Agent tidak ditemukan. Buat agent pertama Anda!",
            "No documents uploaded.": "Belum ada dokumen yang diunggah.",
            "+ Add Knowledge File": "+ Tambah File Pengetahuan",
            "Upload error": "Gagal mengunggah",
            "Agent Name": "Nama Agent",
            "Model Engine": "Mesin Model",
            "Agent Products": "Produk Agent",
            "Select products this agent can recommend.": "Pilih produk yang dapat direkomendasikan agent ini.",
            "Select from Catalog": "Pilih dari Katalog",
            "Or Add Manual Item (Optional)": "Atau Tambah Item Manual (Opsional)",
            "Manual Product Name": "Nama Produk Manual",
            "Price (e.g. Rp 50.000)": "Harga (contoh: Rp 50.000)",
            "Short Description": "Deskripsi Singkat",
            "No description": "Tidak ada deskripsi",
            "No products added yet.": "Belum ada produk yang ditambahkan.",
            "Peran & Gaya Bicara (Role & Tone)": "Peran & Gaya Bicara",
            "Pilih peran & sifat AI...": "Pilih peran & sifat AI...",
            "Memilih opsi peran di atas akan otomatis mengisi Instruksi Dasar di bawah.": "Memilih opsi peran di atas akan otomatis mengisi Instruksi Dasar di bawah.",
            "System Prompt": "Prompt Sistem",
            "Define behavior...": "Tentukan perilaku...",
            "Live Simulator": "Simulator Langsung",
            "Thinking...": "Berpikir...",
            "Type something...": "Ketik sesuatu...",
            "Import from Catalog": "Impor dari Katalog",
            "Select products to add to your agent's knowledge base.": "Pilih produk untuk ditambahkan ke basis pengetahuan agent Anda.",
            "No products found in catalog.": "Tidak ada produk di katalog.",
            "Go to Product Manager": "Buka Manajer Produk",
            "Import": "Impor",

            // Bot Builder
            "Please complete bot data!": "Lengkapi data bot dulu!",
            "Failed to create bot": "Gagal membuat bot",
            "Delete this bot?": "Hapus bot ini?",
            "Failed to delete bot": "Gagal menghapus bot",
            "Connect your AI Agents to your preferred platforms.": "Hubungkan Agen AI ke platform pilihan Anda.",
            "Back to List": "Kembali ke Daftar",
            "No bots connected yet.": "Belum ada bot yang terhubung.",
            "Add your first bot": "Tambah bot pertama Anda",
            "Configure New Bot": "Konfigurasi Bot Baru",
            "Link an AI personality to a messaging platform.": "Hubungkan kepribadian AI ke platform pesan.",
            "Bot Name": "Nama Bot",
            "Select AI Agent": "Pilih Agen AI",
            "Choose Agent": "Pilih Agen",
            "No agents found": "Agen tidak ditemukan",
            "Choose Platform": "Pilih Platform",
            "Create Bot Instance": "Buat Instansi Bot",

            // AI Analytics
            "Insight cerdas dari percakapan dan perilaku pelanggan Anda.": "Wawasan cerdas dari percakapan dan perilaku pelanggan Anda.",
            "Generate Report": "Buat Laporan",
            "Chat Resolution": "Resolusi Chat",
            "Avg. Sentiment": "Rata-rata Sentimen",
            "Conversion Rate": "Tingkat Konversi",
            "AI Messages": "Pesan AI",
            "Conversion Funnel": "Corong Konversi",
            "This Week": "Minggu Ini",
            "This Month": "Bulan Ini",
            "Rekomendasi AI": "Rekomendasi AI",
            "Top Customer Intents": "Tujuan Pelanggan Teratas",
            "messages": "pesan",
            "Detailed Chat Sentiment History": "Riwayat Detail Sentimen Chat",
            "Visualisasi tren kepuasan pelanggan secara harian akan muncul di sini menggunakan": "Visualisasi tren kepuasan pelanggan secara harian akan muncul di sini menggunakan",
            "Connect Analytics Database": "Hubungkan Database Analitik",

            // Integrations
            "Integrations": "Integrasi",
            "Manage your chatbot connections and live channels.": "Kelola koneksi chatbot dan saluran langsung Anda.",
            "Cleanup": "Bersihkan",
            "Add Connection": "Tambah Koneksi",
            "Select Platform": "Pilih Platform",
            "Active Connections": "Koneksi Aktif",
            "Disconnect integration?": "Putuskan integrasi?",
            "Belum ada bot yang dibuat Bang.": "Belum ada bot yang dibuat Bang.",
            "Pergi ke Bot Builder dulu yuk \uD83D\uDE80": "Pergi ke Bot Builder dulu yuk \uD83D\uDE80",
            "Scan QR Code": "Pindai Kode QR",
            "Link your chatbot in seconds.": "Hubungkan chatbot Anda dalam hitungan detik.",
            "Live Preview": "Pratinjau Langsung",
            "Widget Title": "Judul Widget",
            "Theme Color": "Warna Tema",
            "Welcome Message": "Pesan Selamat Datang",
            "Create Widget & Get Code": "Buat Widget & Dapatkan Kode",
            "Select Bot to Connect": "Pilih Bot untuk Dihubungkan",
            "Choose a bot from Builder": "Pilih bot dari Builder",
            "Skip (Broadcast Only / Manual Chat)": "Lewati (Hanya Broadcast / Chat Manual)",
            "Start Connection & Get QR": "Mulai Koneksi & Dapatkan QR",
            "Scan with your phone": "Pindai dengan ponsel Anda",
            "Open WhatsApp > Settings > Linked Devices to scan this code.": "Buka WhatsApp > Pengaturan > Perangkat Tertaut untuk memindai kode ini.",
            "I've Scanned": "Saya Sudah Pindai",
            "Success!": "Berhasil!",
            "Finish": "Selesai",
            "Connect": "Hubungkan",
            "Online": "Online",
            "Offline": "Offline",

            // Notifications
            "Pusat aktivitas real-time sistem Anda.": "Pusat aktivitas waktu nyata sistem Anda.",
            "Delete All": "Hapus Semua",
            "Mark All Read": "Tandai Semua Dibaca",
            "Unread": "Belum Dibaca",
            "AI Bot": "Bot AI",
            "Select All": "Pilih Semua",
            "Delete this notification?": "Hapus notifikasi ini?",
            "Delete selected notifications?": "Hapus notifikasi yang dipilih?",
            "Kategori ini kosong": "Kategori ini kosong",

            // Payments
            "Payments & Automation": "Pembayaran & Otomatisasi",
            "Kelola integrasi pembayaran dan sistem otomatisasi.": "Kelola integrasi pembayaran dan sistem otomatisasi.",
            "AI Closing Logic": "Logika Penutupan AI",
            "Atur skenario closing otomatis untuk Bot Anda.": "Atur skenario closing otomatis untuk Bot Anda.",
            "AI Closing Mode": "Mode Penutupan AI",
            "ACTIVE": "AKTIF",
            "DISABLED": "NONAKTIF",
            "Smart AI Closing": "Penutupan AI Pintar",
            "Aktifkan deteksi niat beli dan kirim invoice otomatis ke pelanggan.": "Aktifkan deteksi niat beli dan kirim invoice otomatis ke pelanggan.",
            "Setup Bot Logic": "Atur Logika Bot",
            "Connected Gateways": "Gateway Terhubung",
            "NEEDS SETUP": "PERLU PENGATURAN",
            "CONNECTED": "TERHUBUNG",
            "Virtual Account & QRIS": "Virtual Account & QRIS",
            "Terima dana otomatis tanpa konfirmasi manual.": "Terima dana otomatis tanpa konfirmasi manual.",
            "Configure API Keys": "Konfigurasi Kunci API",
            "Anti-Fraud Protection Active": "Perlindungan Anti-Fraud Aktif",
            "Settlements": "Penyelesaian",
            "Full History": "Riwayat Lengkap",
            "Security": "Keamanan",
            "Smart Logic": "Logika Pintar",
            "Trigger Keywords": "Kata Kunci Pemicu",
            "Bot Closing Message": "Pesan Penutupan Bot",
            "Save Bot Logic": "Simpan Logika Bot",
            "Discard": "Batalkan",
            "Midtrans Keys": "Kunci Midtrans",
            "Production Mode": "Mode Produksi",
            "Merchant ID": "Merchant ID",
            "Server Key": "Server Key",
            "Save & Connect": "Simpan & Hubungkan",

            // Users
            "Users": "Pengguna",
            "Manage and monitor all users in the system.": "Kelola dan pantau semua pengguna dalam sistem.",
            "Add User": "Tambah Pengguna",
            "Name": "Nama",
            "Email": "Email",
            "Role": "Peran",
            "Actions": "Aksi",
            "Previous": "Sebelumnya",
            "Next": "Berikutnya",
            "Showing": "Menampilkan",
            "of": "dari",
            "users": "pengguna",
            "Logout": "Keluar",
            "US": "PG",
            "Knowledge Base": "Basis Pengetahuan",
            "Live Chat / Inbox": "Chat Langsung / Inbox",
            "Campaign / Broadcast": "Kampanye / Broadcast",
            "Loading...": "Memuat...",
        }
    };

    const t = (key: string) => {
        if (!mounted) return key; // Return key initial render to avoid mismatch if needed, or default
        return dictionary[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
